linters:
  LinterName:
    enabled: false
  PropertySortOrder:
    enabled: false
  StringQuotes:
    style: double_quotes
  SelectorFormat:
    enabled: true
    convention: strict_BEM
  NestingDepth:
    max_depth: 4 